apiVersion: v1
kind: Service
metadata:
  labels:
    component: api-server
  name: api-server-svc
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    component: api-server
