apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    component: api-server
spec:
  template:
    metadata:
      labels:
        component: api-server
    spec:
      containers:
        - name: hermes
          image: docker.io/traefik/whoami:latest
          env:
            - name: WHOAMI_PORT_NUMBER
              value: "8082"
          ports:
            - containerPort: 8082
