apiVersion: apps/v1
kind: Deployment
metadata:
  name: theia
  labels:
    component: theia
spec:
  template:
    metadata:
      labels:
        component: theia
    spec:
      containers:
        - name: hermes
          image: docker.io/traefik/whoami:latest
          env:
            - name: WHOAMI_PORT_NUMBER
              value: "80"
          ports:
            - containerPort: 80
